# Generated by Django 3.2 on 2023-06-06 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, error_messages={'max_length': 'First name is too long.'}, help_text='Add your first name.', max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, error_messages={'max_length': 'Last name is too long.'}, help_text='Add your last name.', max_length=150, null=True, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, error_messages={'max_length': 'Phone number is too long.'}, help_text='Add your phone number.', max_length=15, null=True, verbose_name='phone number')),
                ('address', models.CharField(blank=True, error_messages={'max_length': 'Address is too long.'}, help_text='Add your address.', max_length=255, null=True, verbose_name='address')),
                ('district', models.CharField(blank=True, choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad')], error_messages={'max_length': 'District is too long.'}, help_text='Add your district.', max_length=255, null=True, verbose_name='district')),
                ('pincode', models.CharField(blank=True, error_messages={'max_length': 'Pincode is too long.'}, help_text='Add your pincode.', max_length=6, null=True, verbose_name='pincode')),
                ('dateofbirth', models.DateField(blank=True, help_text='Add your date of birth.', null=True, verbose_name='date of birth')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], error_messages={'max_length': 'Blood group is too long.'}, help_text='Add your blood group.', max_length=3, null=True, verbose_name='blood group')),
                ('last_donated_on', models.DateField(blank=True, help_text='Add your last donated on.', null=True, verbose_name='last donated on')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ('user__email',),
            },
        ),
    ]
