# Generated by Django 3.2 on 2023-06-06 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_verification_link', models.CharField(blank=True, error_messages={'max_length': 'Telegram verification link is too long.'}, help_text='Add your telegram verification link.', max_length=255, null=True, verbose_name='telegram verification link')),
                ('chat_id', models.CharField(blank=True, error_messages={'max_length': 'Chat id is too long.'}, help_text='Add your chat id.', max_length=255, null=True, verbose_name='chat id')),
                ('is_telegram_verified', models.BooleanField(default=False, help_text='Designates whether this user has verified their telegram.', verbose_name='telegram verified status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegramdata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
