# Generated by Django 3.2 on 2023-06-06 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequesthandling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequirement',
            name='date_of_request',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of request.'),
            preserve_default=False,
        ),
    ]
